version: '2'
services:
  rx:
    image: localhost:5000/loadrxdata
    ports:
      - '5555:5555'
    command: python3 main.py -e psql -ht 192.168.48.33 -d LoadRX -n postgres -p 1111 -pr 5436
    restart: always